In [1]:
import numpy as np

N Reynas

In [10]:
import numpy as np

def N_Reynas():
    # Función para verificar si una reina puede colocarse en (fila, col) sin ser atacada
    def es_valido(tablero, fila, col, n):
        # Verifica que no haya otra reina en la misma columna
        for k in range(fila):
            if tablero[k][col] == 1:
                return False

        # Verifica la diagonal superior izquierda
        for k in range(1, n):
            if fila - k >= 0 and col - k >= 0 and tablero[fila - k][col - k] == 1:
                return False

        # Verifica la diagonal superior derecha
        for k in range(1, n):
            if fila - k >= 0 and col + k < n and tablero[fila - k][col + k] == 1:
                return False

        return True

    # Función principal que usa una pila para resolver el problema de manera iterativa
    def solve_iterativo(n):
        tablero = np.zeros((n, n), dtype=int)
        pila = []  # Pila para realizar la búsqueda en profundidad
        fila = 0
        col = 0

        while fila < n:
            colocado = False
            while col < n:
                if es_valido(tablero, fila, col, n):
                    tablero[fila][col] = 1
                    pila += [(fila, col)]  # Guarda la posición de la reina
                    fila += 1
                    col = 0
                    colocado = True
                    break
                col += 1

            if not colocado:
                if not pila:
                    return False, tablero  # No hay solución
                fila, col = pila[-1]  # Regresa a la última posición
                pila = pila[:-1]  # Elimina la última posición de la pila
                tablero[fila][col] = 0  # Elimina la reina de esa posición
                col += 1  # Intenta la siguiente columna

        return True, tablero

    # Solicita al usuario el número de reinas
    n = int(input("¿Cuántas reinas deseas colocar? "))

    # Llama a la función iterativa para resolver el problema
    resuelto, tablero_final = solve_iterativo(n)

    # Muestra el resultado
    if resuelto:
        print("Se ha encontrado una solución:")
        print(tablero_final)
    else:
        print("No se ha encontrado una solución.")

# Llamada a la función
N_Reynas()

Se ha encontrado una solución:
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


In [9]:
import numpy as np
def Sodoku():
    print ("Bienvenido al juego de Sudoku")
    print ("El tablero es de 16x16")
    print ("Tablero actual es:")
    tablero = np.array([
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    ])
    print(tablero)

    def es_valido(tablero, fila, col, num):
        # Verifica la fila
        if num in tablero[fila]:
            return False

        # Verifica la columna
        if num in tablero[:, col]:
            return False

        # Verifica el subcuadro 4x4
        subcuadro_fila = fila // 4 * 4
        subcuadro_col = col // 4 * 4
        if num in tablero[subcuadro_fila:subcuadro_fila + 4, subcuadro_col:subcuadro_col + 4]:
            return False

        return True

    def resolver_sudoku(tablero):
        for fila in range(16):
            for col in range(16):
                if tablero[fila][col] == 0:
                    for num in range(1, 17):
                        if es_valido(tablero, fila, col, num):
                            tablero[fila][col] = num
                            if resolver_sudoku(tablero):
                                return True
                            tablero[fila][col] = 0
                    return False
        return True 
    if resolver_sudoku(tablero):
        print("Se ha resuelto el Sudoku:")
        print(tablero)
    else:
        print("No se pudo resolver el Sudoku.")
    

Sodoku()

Bienvenido al juego de Sudoku
El tablero es de 16x16
Tablero actual es:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Se ha resuelto el Sudoku:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 5  6  7  8  1  2  3  4 13 14 15 16  9 10 11 12]
 [ 9 10 11 12 13 14 15 16  1  2  3  4  5  6  7  8]
 [13 14 15 16  9 10 11 12  5  6  7  8  1  2  3  4]
 [ 2  1  4  3  6  5  8  7 10  9 12 11 14 13 16 15]
 [ 6  5  8  7  2  1  4  3 14 13 16 15 10  9 12 11]
 [10  9 12 11 14 13 16 15  2  1  4 

In [11]:
N_Reynas()

Se ha encontrado una solución:
[[0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]]
