In [3]:
#para quitar recursividad solo podemos ocupar tres lineas
import numpy as np



def n_reinas(n):
  def resolvedor(tablero, filas):
    if filas == n :    ##Ya se recorrieron todas las posible filas del tablero
      imprimir_tablero(tablero,n)
      return True


    for col in range(n):
      validez = True ##Valido es true cuando se puede poner una reina en una posicion
      i = 0
      while i < filas:
        if tablero[i] == col or tablero[i] - i == col - filas or tablero[i] + i == col + filas:
          validez = False
          break

        i = i+1
      if validez:
         tablero[filas] = col   ## Ahora evalua las filas que se van evaluando autmaticamente
         ## Aqui viene la solucion de la forma iterativa
         imprimir_tablero (tablero,n)
         if resolvedor (tablero, filas + 1):
          return True
         print (f"Backtracking: Retirando la reina de la fila {filas}, columna {col}")
         tablero[filas] = -1
          ####


    return False

  def imprimir_tablero(tablero,n):
      tablerito = np.zeros((n,n))
      for i in range (n):
        for j in range (n):
          if tablero[i] == j:
            tablerito [i,j] = 1
      print(tablerito)


  tablero = [-1]*n
  if not resolvedor(tablero,0):
   print ("No hay solución")




n_reinas(4)


[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Backtracking: Retirando la reina de la fila 1, columna 2
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Backtracking: Retirando la reina de la fila 2, columna 1
Backtracking: Retirando la reina de la fila 1, columna 3
Backtracking: Retirando la reina de la fila 0, columna 0
[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
